services:
  laminas:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
  postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_DB=teste-treinacon
        ports:
            - '8004:5432'
